Repository projectclarify/clarify, pull requests merged in 2020-01, with the labels that each got.

#114 testing
  .circleci/config.yml
  tools/environments/base/Dockerfile
  tools/environments/base/install_base.sh
  tools/environments/base/install_tf.sh
  tools/testing/test_circle.sh
Labels: approved, lgtm, size/M

#117 remove outdated fyre readme
  clarify/batch/README.md
Labels: approved, lgtm, size/L

#118 presubmit still works?
  README.md
  tools/prow/config.yaml
  tools/prow/helper.py
  tools/testing/test_prow.sh
Labels: approved, lgtm, size/M

#119 Prow updates vis repo name and num cpus
  README.md
  tools/environments/build.py
  tools/environments/install/setup_workspace.sh
  tools/kube/update_profiles.py
  tools/prow/config.yaml
  tools/prow/helper.py
  tools/prow/plugins.yaml
  tools/testing/README.md
  tools/testing/test_circle.sh
  tools/testing/test_prow.sh
Labels: approved, lgtm

#120 prow dev
  tools/prow/helper.py
Labels: approved, lgtm, size/XS

#135 Jobs complete 1
  .bazelrc
  clarify/batch/BUILD
  clarify/batch/fyre_test.py
  clarify/batch/job.py
  clarify/batch/job_test.py
  clarify/batch/jobs.py
Labels: approved, lgtm, size/M

#150 bump trax version so demo works
  dev-requirements.txt
Labels: approved, lgtm, size/XS

#151 myname-dasheng
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#152 name, test PR
  .gitignore
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#153 my file is saarangp
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#154 added untitled.txt
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#155 hmallen99
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#156 my name
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#167 restyled config
  .restyled.yaml
Labels: approved, lgtm, size/S

#177 check yapf diff on circle
  .circleci/config.yml
  clarify/batch/fyre.py
  clarify/batch/fyre_test.py
  clarify/batch/git_utils.py
  clarify/batch/git_utils_test.py
  clarify/batch/job.py
  clarify/batch/job_test.py
  clarify/batch/jobs.py
  clarify/batch/jobs_test.py
  clarify/datasets/core/cbt_datagen.py
  clarify/datasets/deap/problems_test.py
  clarify/research/eeg_ssl/models.py
  clarify/research/eeg_ssl/models_test.py
  clarify/research/gmcl/models.py
  clarify/research/gmcl/models_test.py
  clarify/research/image_fec/models.py
  clarify/research/image_fec/models_test.py
  clarify/research/train.py
  clarify/research/vid_fec/models.py
  clarify/research/vid_fec/models_test.py
  clarify/serve/label_state/gcf/main.py
  clarify/serve/utils/kfserving_utils.py
  clarify/utils/cbt_utils_test.py
  tools/testing/check_yapf.py
  tools/testing/clean_yapf.sh
Labels: approved, lgtm, size/XL

#178 patch readame, check presubmits ignore
  README.md
Labels: approved, lgtm, retest-not-required-docs-only, size/XS

#174 Minimalist PR with username
  exp/untitled.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#192 Adding my name to untitled.txt
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#191 remove extra info from front page
  client/src/components/view-article-project-clarify.ts
Labels: approved, lgtm, needs-ok-to-test, size/L
