Repository projectclarify/clarify, pull requests merged in 2020-02, with the labels that each got.

#193 Adding my name to untitled.txt
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/XS

#194 image fec subproject layout
  clarify/research/image_fec/OWNERS
  clarify/research/image_fec/README.md
  clarify/research/image_fec/docs.ipynb
Labels: approved, do-not-merge/invalid-owners-file, size/M

#195 Initial outline of sweet manuscript / demo combo.
  clarify/research/image_fec/docs.ipynb
Labels: approved, size/XL

#197 eeg ssl starting point
  clarify/research/eeg_ssl/OWNERS
  clarify/research/eeg_ssl/README.md
  clarify/research/eeg_ssl/docs.ipynb
Labels: approved, size/XL

#198 updated notebook
  clarify/research/eeg_ssl/docs.ipynb
Labels: approved, size/L

#199 fx dev notebook
  client/OWNERS
  client/README.md
  client/fx-dev.ipynb
Labels: approved, do-not-merge/invalid-owners-file, size/XXL

#200 fix dev notebook readme link
  client/README.md
Labels: approved, retest-not-required-docs-only

#175 Confirmed cpython-compile go is multithreaded
  .gitignore
  exp/golang-experiments/cpython-parallel/go-threading-test.go
  exp/golang-experiments/cpython-parallel/go-threading-test.h
  exp/golang-experiments/cpython-parallel/go-threading-test.py
  exp/untitled.txt
Labels: approved, lgtm, ok-to-test, size/L

#204 fix bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, retest-not-required-docs-only, size/S

#158 myname is Chris
  exp/untitled.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#208 patch readmes and docs deploy
  .github/workflows/deploy-docs.yaml
  README.md
  docs/README.md
Labels: approved, size/M
